/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import MemoriaReglas.Empresa;
import Modelo.Color;
import Modelo.Modelo;
import javax.swing.JOptionPane;
import static javax.swing.UIManager.get;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chris
 */
public class GestionarModeloModifBaja extends javax.swing.JFrame {
    private Presentador.PresentadorGestionarModelos presentador;
    /**
     * Creates new form GestionarModeloModifBaja
     */
    public GestionarModeloModifBaja() {
       
        initComponents();
        inicializarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaModelos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        modificar = new javax.swing.JButton();
        borrar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaModelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaModelos);

        jLabel1.setText("Modelos");

        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        borrar.setText("Borrar");
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(modificar)
                        .addGap(72, 72, 72)
                        .addComponent(borrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modificar)
                    .addComponent(borrar)
                    .addComponent(cancelar))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
    if (tablaModelos.getSelectedRow() <=-1)
            mostrarMensajeErrorFila();
        else
            {
            int m = Integer.parseInt((String) tablaModelos.getValueAt(tablaModelos.getSelectedRow(), 0));
            GestionarModeloModif g = new GestionarModeloModif(m);
            g.setVisible(true);
    }//GEN-LAST:event_modificarActionPerformed
    }
    
    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        if (tablaModelos.getSelectedRow() <=-1)
            mostrarMensajeErrorFila();
        else
            {            
            Object[] o = new Object[3];
            o[0] = tablaModelos.getValueAt(tablaModelos.getSelectedRow(), 0);
            o[1] = tablaModelos.getValueAt(tablaModelos.getSelectedRow(), 1);
            o[2] = tablaModelos.getValueAt(tablaModelos.getSelectedRow(), 2);
            
            
            presentador.borrarModelo((int) o[0]);
            
    }//GEN-LAST:event_borrarActionPerformed
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrar;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modificar;
    private javax.swing.JTable tablaModelos;
    // End of variables declaration//GEN-END:variables

    public void inicializarTabla() {
        DefaultTableModel matriz= new DefaultTableModel();       
        matriz.addColumn("SKU");
        matriz.addColumn("Descripcion");
        matriz.addColumn("Objetivo");
        
       for(Modelo m : Empresa.getMod())
       {
           Object []f = new Object[3];
            f[0]= m.getSKU();
            f[1]= m.getDescripcionMod();
            f[2]= m.getObjetivo();
            matriz.addRow(f);
       }
       tablaModelos.setModel(matriz);
    }
        public void mostrarMensajeErrorFila() {
         JOptionPane.showMessageDialog(this, "Por favor seleccionar fila en tabla","Error",JOptionPane.ERROR_MESSAGE);
    }
       
    public void mostrarMensajeModificacion() {
         JOptionPane.showMessageDialog(this, "Color modificado exitosamente","Exito",JOptionPane.INFORMATION_MESSAGE);
    }
    
    public void mostrarMensajeBorrado() {
        JOptionPane.showMessageDialog(this, "Color borrado exitosamente","Exito",JOptionPane.INFORMATION_MESSAGE);
    }
}
